### ISSUE TITLE
See the effect of a slice profile with a 3D phantom.

### ISSUE THREAD

**Issue by ZemaTimoteo** [mzaiss/MRTwin_pulseq#14]
I would like to use the simulation software to understand what is the effect of my sequence on the slice profile, more specifically, I would like to understand what is the effective slice thickness for a sync RF pulse which I designed. 

In order to do so, I would need a 3D phantom. 

Would it be possible with MRTwin to do that?

Looking forward to hear from you

Best
Tiago

**Comment by mzaiss** [comment]
Our simulation does currently not support slice selection.

but simple slice selection can be calculated rather easily

check

https://github.com/pulseq/MR-Physics-with-Pulseq/tree/main/tutorials/02_rf_pulses

and

https://github.com/pulseq/MR-Physics-with-Pulseq/blob/main/slides/D1-1320-RF_Pulses_Tony_Stoecker.pdf



ZemaTimoteo ***@***.***> schrieb am Di., 16. Apr. 2024, 12:51:
