### ISSUE TITLE
platform independence

### ISSUE THREAD

**Issue by mzaiss** [mzaiss/MRTwin_pulseq#7]
windows not always works
![grafik](https://user-images.githubusercontent.com/8328474/224674015-6d76ac44-9eab-40b6-b64a-1dd863cd01f2.png)

need to check different pythinsm pips etc. to be clear about the dependencies

**Comment by J-Endres** [comment]
The mrzero core package now specifies the minimum supported versions. If those are installed and it still does not run, we can reopen this issue
